"""
llm_semantic_scanner.py
-----------------------
Replaces hardcoded regex fraud keywords by dynamically scanning OCR text
using a local Ollama LLM. The LLM is instructed to identify AI spelling
hallucinations, fictional institutions, and placeholder text, returning
a strictly formatted JSON array of conflicts.
"""

from __future__ import annotations

import json
import logging
import textwrap
import urllib.request
import urllib.error
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class LLMSemanticScanner:
    """
    Scans OCR text for semantic fraud using a local Ollama model.
    Returns a list of conflict dicts compatible with TrustEngine.
    """

    def __init__(
        self,
        base_url: str = "http://localhost:11434",
        model: str = "llama3.2:1b",
        timeout: int = 120,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout = timeout

    def _post_json(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Send a JSON POST request and return the parsed response."""
        url = f"{self.base_url}{endpoint}"
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))

    def scan_text(self, full_text: str) -> List[Dict[str, Any]]:
        """
        Scan OCR text for semantic fraud.
        Returns a list of dicts: {"type": str, "severity": "HIGH"|"MEDIUM", "message": str}
        """
        if not full_text or len(full_text.strip()) < 10:
            return []

        # We must instruct the LLM very strictly to output ONLY JSON.
        system_prompt = textwrap.dedent("""\
            You are an expert fraud detection AI for a banking system.
            You will be given the raw OCR text extracted from a document.
            Your task is to identify indicators that the document is fake, generated by AI, or a template.

            LOOK FOR:
            1. Fictional / unregistered institutions (e.g., "Apex National Finance", "Example Bank", "Fictional").
            2. Placeholder text or watermarks (e.g., "SAMPLE", "VOID", "BARCODE", "For Demonstration").
            3. AI Spelling Hallucinations (e.g., gibberish words, obvious misspellings like "Electrmics", "Canpus").

            OUTPUT FORMAT:
            You must output a strictly valid JSON array of objects. Do not include markdown code blocks (like ```json), just the raw JSON string. If no fraud signals are detected, output an empty array: []

            JSON Object Schema:
            {
              "type": "string (e.g., unregistered_institution, placeholder_text, spelling_hallucination)",
              "severity": "string (must be HIGH or MEDIUM)",
              "message": "string (detailed explanation of what was found)"
            }
        """)

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"OCR TEXT TO ANALYZE:\n{full_text}"},
            ],
            "stream": False,
            "format": "json",  # Force Ollama to output JSON structure
            "options": {
                "temperature": 0.0,  # Fully deterministic
                "num_predict": 300,
            },
        }

        try:
            response = self._post_json("/api/chat", payload)
            content = response.get("message", {}).get("content", "").strip()
            
            if not content:
                return []
                
            conflicts = json.loads(content)
            
            # Tiny models often wrap arrays in a dictionary (e.g., {"conflicts": [...]})
            if isinstance(conflicts, dict):
                # Try to extract the first list found in the dict values
                for v in conflicts.values():
                    if isinstance(v, list):
                        conflicts = v
                        break
                # If still a dict, maybe it's a single conflict object?
                if isinstance(conflicts, dict) and "type" in conflicts:
                    conflicts = [conflicts]

            if isinstance(conflicts, list):
                # Ensure structure is valid before returning
                valid_conflicts = []
                for c in conflicts:
                    if isinstance(c, dict) and "severity" in c and "message" in c:
                        # Normalize severity
                        sev = c["severity"].upper()
                        if sev not in ("HIGH", "MEDIUM", "LOW"):
                            sev = "MEDIUM"
                        valid_conflicts.append({
                            "type": str(c.get("type", "semantic_fraud")),
                            "severity": sev,
                            "message": str(c["message"]),
                        })
                
                if valid_conflicts:
                    logger.warning(
                        "LLMSemanticScanner detected %d signals: %s", 
                        len(valid_conflicts),
                        [c["type"] for c in valid_conflicts]
                    )
                return valid_conflicts
            else:
                logger.error("LLMSemanticScanner: output was not a JSON array or recognizable object. Got: %s. Content: %s", type(conflicts), content)
                return []

        except urllib.error.URLError as exc:
            logger.warning("LLMSemanticScanner: Ollama server unavailable or timed out (%s). Returning empty list.", exc)
            return []
        except json.JSONDecodeError as exc:
            logger.error("LLMSemanticScanner: Failed to parse JSON from LLM: %s", exc)
            return []
        except Exception as exc:  # pylint: disable=broad-except
            logger.error("LLMSemanticScanner: Unexpected error: %s", exc)
            return []
